# Generated by Django 6.1.1 on 2026-09-27 00:24

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_alter_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="emb",
            field=models.BinaryField(default=movie.models.get_default_array),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                default="movie/images/default.jpg", upload_to="movie/images/"
            ),
        ),
    ]
